<?php

/**
 * BaseFilmGenre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $film_id
 * @property integer $genre_id
 * @property Film $Film
 * @property Genre $Genre
 * 
 * @method integer   getFilmId()   Returns the current record's "film_id" value
 * @method integer   getGenreId()  Returns the current record's "genre_id" value
 * @method Film      getFilm()     Returns the current record's "Film" value
 * @method Genre     getGenre()    Returns the current record's "Genre" value
 * @method FilmGenre setFilmId()   Sets the current record's "film_id" value
 * @method FilmGenre setGenreId()  Sets the current record's "genre_id" value
 * @method FilmGenre setFilm()     Sets the current record's "Film" value
 * @method FilmGenre setGenre()    Sets the current record's "Genre" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFilmGenre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('film_genre');
        $this->hasColumn('film_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('genre_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Film', array(
             'local' => 'film_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Genre', array(
             'local' => 'genre_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}