<?php

/**
 * BaseFestivalEditionStire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stire_id
 * @property integer $festival_edition_id
 * @property Stire $Stire
 * @property FestivalEdition $FestivalEdition
 * 
 * @method integer              getStireId()             Returns the current record's "stire_id" value
 * @method integer              getFestivalEditionId()   Returns the current record's "festival_edition_id" value
 * @method Stire                getStire()               Returns the current record's "Stire" value
 * @method FestivalEdition      getFestivalEdition()     Returns the current record's "FestivalEdition" value
 * @method FestivalEditionStire setStireId()             Sets the current record's "stire_id" value
 * @method FestivalEditionStire setFestivalEditionId()   Sets the current record's "festival_edition_id" value
 * @method FestivalEditionStire setStire()               Sets the current record's "Stire" value
 * @method FestivalEditionStire setFestivalEdition()     Sets the current record's "FestivalEdition" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFestivalEditionStire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('festival_edition_stire');
        $this->hasColumn('stire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('festival_edition_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stire', array(
             'local' => 'stire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FestivalEdition', array(
             'local' => 'festival_edition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}