<?php

/**
 * BaseGenre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Films
 * @property Doctrine_Collection $FilmGenre
 * @property Doctrine_Collection $CinemaService
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getFilms()         Returns the current record's "Films" collection
 * @method Doctrine_Collection getFilmGenre()     Returns the current record's "FilmGenre" collection
 * @method Doctrine_Collection getCinemaService() Returns the current record's "CinemaService" collection
 * @method Genre               setName()          Sets the current record's "name" value
 * @method Genre               setFilms()         Sets the current record's "Films" collection
 * @method Genre               setFilmGenre()     Sets the current record's "FilmGenre" collection
 * @method Genre               setCinemaService() Sets the current record's "CinemaService" collection
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGenre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('genre');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Film as Films', array(
             'refClass' => 'FilmGenre',
             'local' => 'genre_id',
             'foreign' => 'film_id'));

        $this->hasMany('FilmGenre', array(
             'local' => 'id',
             'foreign' => 'genre_id'));

        $this->hasMany('CinemaService', array(
             'local' => 'id',
             'foreign' => 'service_id'));
    }
}