<?php

/**
 * BaseFilmArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $film_id
 * @property Article $Article
 * @property Film $Film
 * 
 * @method integer     getArticleId()  Returns the current record's "article_id" value
 * @method integer     getFilmId()     Returns the current record's "film_id" value
 * @method Article     getArticle()    Returns the current record's "Article" value
 * @method Film        getFilm()       Returns the current record's "Film" value
 * @method FilmArticle setArticleId()  Sets the current record's "article_id" value
 * @method FilmArticle setFilmId()     Sets the current record's "film_id" value
 * @method FilmArticle setArticle()    Sets the current record's "Article" value
 * @method FilmArticle setFilm()       Sets the current record's "Film" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFilmArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('film_article');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('film_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Film', array(
             'local' => 'film_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}