<?php

/**
 * BaseFestival
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $imdb_key
 * @property FestivalEdition $FestivalEdition
 * 
 * @method string          getName()            Returns the current record's "name" value
 * @method string          getImdbKey()         Returns the current record's "imdb_key" value
 * @method FestivalEdition getFestivalEdition() Returns the current record's "FestivalEdition" value
 * @method Festival        setName()            Sets the current record's "name" value
 * @method Festival        setImdbKey()         Sets the current record's "imdb_key" value
 * @method Festival        setFestivalEdition() Sets the current record's "FestivalEdition" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFestival extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('festival');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('imdb_key', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FestivalEdition', array(
             'local' => 'id',
             'foreign' => 'festival_id'));
    }
}