<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticleCategory
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getArticles()        Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticleCategory() Returns the current record's "ArticleCategory" collection
 * @method Category            setName()            Sets the current record's "name" value
 * @method Category            setArticles()        Sets the current record's "Articles" collection
 * @method Category            setArticleCategory() Sets the current record's "ArticleCategory" collection
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleCategory',
             'local' => 'category_id',
             'foreign' => 'article_id'));

        $this->hasMany('ArticleCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}