<?php

/**
 * BasePersonVideoAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $person_id
 * @property integer $album_id
 * @property Person $Person
 * @property VideoAlbum $VideoAlbum
 * 
 * @method integer          getPersonId()   Returns the current record's "person_id" value
 * @method integer          getAlbumId()    Returns the current record's "album_id" value
 * @method Person           getPerson()     Returns the current record's "Person" value
 * @method VideoAlbum       getVideoAlbum() Returns the current record's "VideoAlbum" value
 * @method PersonVideoAlbum setPersonId()   Sets the current record's "person_id" value
 * @method PersonVideoAlbum setAlbumId()    Sets the current record's "album_id" value
 * @method PersonVideoAlbum setPerson()     Sets the current record's "Person" value
 * @method PersonVideoAlbum setVideoAlbum() Sets the current record's "VideoAlbum" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonVideoAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_video_album');
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('VideoAlbum', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}