<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property string $description
 * @property enum $state
 * @property integer $album_id
 * @property PhotoAlbum $Album
 * 
 * @method string     getFilename()    Returns the current record's "filename" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method enum       getState()       Returns the current record's "state" value
 * @method integer    getAlbumId()     Returns the current record's "album_id" value
 * @method PhotoAlbum getAlbum()       Returns the current record's "Album" value
 * @method Photo      setFilename()    Sets the current record's "filename" value
 * @method Photo      setDescription() Sets the current record's "description" value
 * @method Photo      setState()       Sets the current record's "state" value
 * @method Photo      setAlbumId()     Sets the current record's "album_id" value
 * @method Photo      setAlbum()       Sets the current record's "Album" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('filename', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => -1,
              1 => 0,
              2 => 1,
             ),
             ));
        $this->hasColumn('on_home', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('is_redcarpet', 'bool', null, array(
             'type' => 'bool',
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PhotoAlbum as Album', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'album_id',
             ),
             ));
        $this->actAs($sortable0);
		
		$timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}