<?php

/**
 * BaseFestivalSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $imdb_key
 * @property integer $festival_edition_id
 * @property Doctrine_Collection $Persons
 * @property FestivalEdition $FestivalEdition
 * @property Doctrine_Collection $FestivalSectionPerson
 * @property Doctrine_Collection $FestivalSectionParticipant
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getImdbKey()                    Returns the current record's "imdb_key" value
 * @method integer             getFestivalEditionId()          Returns the current record's "festival_edition_id" value
 * @method Doctrine_Collection getPersons()                    Returns the current record's "Persons" collection
 * @method FestivalEdition     getFestivalEdition()            Returns the current record's "FestivalEdition" value
 * @method Doctrine_Collection getFestivalSectionPerson()      Returns the current record's "FestivalSectionPerson" collection
 * @method Doctrine_Collection getFestivalSectionParticipant() Returns the current record's "FestivalSectionParticipant" collection
 * @method FestivalSection     setName()                       Sets the current record's "name" value
 * @method FestivalSection     setImdbKey()                    Sets the current record's "imdb_key" value
 * @method FestivalSection     setFestivalEditionId()          Sets the current record's "festival_edition_id" value
 * @method FestivalSection     setPersons()                    Sets the current record's "Persons" collection
 * @method FestivalSection     setFestivalEdition()            Sets the current record's "FestivalEdition" value
 * @method FestivalSection     setFestivalSectionPerson()      Sets the current record's "FestivalSectionPerson" collection
 * @method FestivalSection     setFestivalSectionParticipant() Sets the current record's "FestivalSectionParticipant" collection
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFestivalSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('festival_section');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('imdb_key', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('festival_edition_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Person as Persons', array(
             'refClass' => 'FestivalSectionPerson',
             'local' => 'festival_section_id',
             'foreign' => 'person_id'));

        $this->hasOne('FestivalEdition', array(
             'local' => 'festival_edition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('FestivalSectionPerson', array(
             'local' => 'id',
             'foreign' => 'festival_section_id'));

        $this->hasMany('FestivalSectionParticipant', array(
             'local' => 'id',
             'foreign' => 'festival_section_id'));
    }
}