<?php

/**
 * BaseFilmStire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stire_id
 * @property integer $film_id
 * @property Stire $Stire
 * @property Film $Film
 * 
 * @method integer   getStireId()  Returns the current record's "stire_id" value
 * @method integer   getFilmId()   Returns the current record's "film_id" value
 * @method Stire     getStire()    Returns the current record's "Stire" value
 * @method Film      getFilm()     Returns the current record's "Film" value
 * @method FilmStire setStireId()  Sets the current record's "stire_id" value
 * @method FilmStire setFilmId()   Sets the current record's "film_id" value
 * @method FilmStire setStire()    Sets the current record's "Stire" value
 * @method FilmStire setFilm()     Sets the current record's "Film" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFilmStire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('film_stire');
        $this->hasColumn('stire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('film_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stire', array(
             'local' => 'stire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Film', array(
             'local' => 'film_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}