<?php

/**
 * BasePersonStire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stire_id
 * @property integer $person_id
 * @property Stire $Stire
 * @property Person $Person
 * 
 * @method integer     getStireId()   Returns the current record's "stire_id" value
 * @method integer     getPersonId()  Returns the current record's "person_id" value
 * @method Stire       getStire()     Returns the current record's "Stire" value
 * @method Person      getPerson()    Returns the current record's "Person" value
 * @method PersonStire setStireId()   Sets the current record's "stire_id" value
 * @method PersonStire setPersonId()  Sets the current record's "person_id" value
 * @method PersonStire setStire()     Sets the current record's "Stire" value
 * @method PersonStire setPerson()    Sets the current record's "Person" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonStire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_stire');
        $this->hasColumn('stire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stire', array(
             'local' => 'stire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}