<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property enum $state
 * @property integer $album_id
 * @property VideoAlbum $Album
 * 
 * @method string     getCode()     Returns the current record's "code" value
 * @method string     getName()     Returns the current record's "name" value
 * @method enum       getState()    Returns the current record's "state" value
 * @method integer    getAlbumId()  Returns the current record's "album_id" value
 * @method VideoAlbum getAlbum()    Returns the current record's "Album" value
 * @method Video      setCode()     Sets the current record's "code" value
 * @method Video      setName()     Sets the current record's "name" value
 * @method Video      setState()    Sets the current record's "state" value
 * @method Video      setAlbumId()  Sets the current record's "album_id" value
 * @method Video      setAlbum()    Sets the current record's "Album" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video');
        $this->hasColumn('code', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => -1,
              1 => 0,
              2 => 1,
             ),
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VideoAlbum as Album', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'album_id',
             ),
             ));
        $this->actAs($sortable0);

		$timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}