<?php

/**
 * BaseHomepage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $background_filename
 * 
 * @method string   getBackgroundFilename()  Returns the current record's "background_filename" value
 * @method Homepage setBackgroundFilename()  Sets the current record's "background_filename" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHomepage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('homepage');
        $this->hasColumn('background_filename', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}