<?php

/**
 * BaseCinemaStire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stire_id
 * @property integer $cinema_id
 * @property Stire $Stire
 * @property Cinema $Cinema
 * 
 * @method integer     getStireId()   Returns the current record's "stire_id" value
 * @method integer     getCinemaId()  Returns the current record's "cinema_id" value
 * @method Stire       getStire()     Returns the current record's "Stire" value
 * @method Cinema      getCinema()    Returns the current record's "Cinema" value
 * @method CinemaStire setStireId()   Sets the current record's "stire_id" value
 * @method CinemaStire setCinemaId()  Sets the current record's "cinema_id" value
 * @method CinemaStire setStire()     Sets the current record's "Stire" value
 * @method CinemaStire setCinema()    Sets the current record's "Cinema" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCinemaStire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cinema_stire');
        $this->hasColumn('stire_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cinema_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stire', array(
             'local' => 'stire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Cinema', array(
             'local' => 'cinema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}