<?php

/**
 * BaseShopFilm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShopFilmBuffer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_film_buffer');
        $this->hasColumn('shop_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('imdb', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('is_dvd', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('dvd_url', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('is_bluray', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bluray_url', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('is_online', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('online_url', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
	}
}