<?php

/**
 * BaseCinemaSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cinema_id
 * @property integer $film_id
 * @property date $day
 * @property string $schedule
 * @property enum $format
 * @property Cinema $Cinema
 * @property Film $Film
 * 
 * @method integer        getCinemaId()  Returns the current record's "cinema_id" value
 * @method integer        getFilmId()    Returns the current record's "film_id" value
 * @method date           getDay()       Returns the current record's "day" value
 * @method string         getSchedule()  Returns the current record's "schedule" value
 * @method enum           getFormat()    Returns the current record's "format" value
 * @method Cinema         getCinema()    Returns the current record's "Cinema" value
 * @method Film           getFilm()      Returns the current record's "Film" value
 * @method CinemaSchedule setCinemaId()  Sets the current record's "cinema_id" value
 * @method CinemaSchedule setFilmId()    Sets the current record's "film_id" value
 * @method CinemaSchedule setDay()       Sets the current record's "day" value
 * @method CinemaSchedule setSchedule()  Sets the current record's "schedule" value
 * @method CinemaSchedule setFormat()    Sets the current record's "format" value
 * @method CinemaSchedule setCinema()    Sets the current record's "Cinema" value
 * @method CinemaSchedule setFilm()      Sets the current record's "Film" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCinemaSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cinema_schedule');
        $this->hasColumn('cinema_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('film_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('day', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('schedule', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('format', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'pelicula',
              1 => 'digital',
              2 => '3d',
             ),
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cinema', array(
             'local' => 'cinema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Film', array(
             'local' => 'film_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}