<?php

/**
 * BaseVisit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $library_id
 * @property string $url
 * @property string $name
 * @property string $ip
 * 
 * @method integer getLibraryId()  Returns the current record's "library_id" value
 * @method string  getUrl()        Returns the current record's "url" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getIp()         Returns the current record's "ip" value
 * @method Visit   setLibraryId()  Sets the current record's "library_id" value
 * @method Visit   setUrl()        Sets the current record's "url" value
 * @method Visit   setName()       Sets the current record's "name" value
 * @method Visit   setIp()         Sets the current record's "ip" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVisit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('visit');
        $this->hasColumn('library_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('url', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('ip', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}