<?php

/**
 * BaseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $country
 * @property string $region
 * @property string $city
 * @property integer $importance
 * @property sfGuardUser $sfGuardUser
 * @property Cinema $Cinema
 * 
 * @method string      getCountry()     Returns the current record's "country" value
 * @method string      getRegion()      Returns the current record's "region" value
 * @method string      getCity()        Returns the current record's "city" value
 * @method integer     getImportance()  Returns the current record's "importance" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Cinema      getCinema()      Returns the current record's "Cinema" value
 * @method Location    setCountry()     Sets the current record's "country" value
 * @method Location    setRegion()      Sets the current record's "region" value
 * @method Location    setCity()        Sets the current record's "city" value
 * @method Location    setImportance()  Sets the current record's "importance" value
 * @method Location    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Location    setCinema()      Sets the current record's "Cinema" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('country', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('region', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('city', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('importance', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'location_id'));

        $this->hasOne('Cinema', array(
             'local' => 'id',
             'foreign' => 'location_id'));
    }
}