<?php

/**
 * BaseCinemaArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $cinema_id
 * @property Article $Article
 * @property Cinema $Cinema
 * 
 * @method integer       getArticleId()  Returns the current record's "article_id" value
 * @method integer       getCinemaId()   Returns the current record's "cinema_id" value
 * @method Article       getArticle()    Returns the current record's "Article" value
 * @method Cinema        getCinema()     Returns the current record's "Cinema" value
 * @method CinemaArticle setArticleId()  Sets the current record's "article_id" value
 * @method CinemaArticle setCinemaId()   Sets the current record's "cinema_id" value
 * @method CinemaArticle setArticle()    Sets the current record's "Article" value
 * @method CinemaArticle setCinema()     Sets the current record's "Cinema" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCinemaArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cinema_article');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cinema_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Cinema', array(
             'local' => 'cinema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}