<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Services
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getServices() Returns the current record's "Services" collection
 * @method Service             setName()     Sets the current record's "name" value
 * @method Service             setServices() Sets the current record's "Services" collection
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cinema as Services', array(
             'refClass' => 'CinemaService',
             'local' => 'service_id',
             'foreign' => 'cinema_id'));
    }
}