<?php

/**
 * BaseFestivalSectionParticipant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $festival_section_id
 * @property string $film_imdb
 * @property string $person_imdb
 * @property bool $is_winner
 * @property FestivalSection $FestivalSection
 * 
 * @method integer                    getFestivalSectionId()   Returns the current record's "festival_section_id" value
 * @method string                     getFilmImdb()            Returns the current record's "film_imdb" value
 * @method string                     getPersonImdb()          Returns the current record's "person_imdb" value
 * @method bool                       getIsWinner()            Returns the current record's "is_winner" value
 * @method FestivalSection            getFestivalSection()     Returns the current record's "FestivalSection" value
 * @method FestivalSectionParticipant setFestivalSectionId()   Sets the current record's "festival_section_id" value
 * @method FestivalSectionParticipant setFilmImdb()            Sets the current record's "film_imdb" value
 * @method FestivalSectionParticipant setPersonImdb()          Sets the current record's "person_imdb" value
 * @method FestivalSectionParticipant setIsWinner()            Sets the current record's "is_winner" value
 * @method FestivalSectionParticipant setFestivalSection()     Sets the current record's "FestivalSection" value
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFestivalSectionParticipant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('festival_section_participant');
        $this->hasColumn('festival_section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('film_imdb', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('person_imdb', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('is_winner', 'bool', null, array(
             'type' => 'bool',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FestivalSection', array(
             'local' => 'festival_section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}