prod:
  aws:
    bucket: "filmsi-prod"
    
dev:
  aws:
    bucket: "filmsi-dev"

all:
  photos:
    aws_s3_folder: 'photos'
    maxfilesize: 5000000
    sourceimage_width: 465
    sourceimage_height: null
    thumbnail_width: 125
    thumbnail_height: 125
    thumbnail_small_width: 125
    thumbnail_small_height: 125
    
  person:
    aws_s3_folder: 'persons'
    maxfilesize: 5000000
    sourceimage_width: 480
    sourceimage_height: null
    thumbnail_width: 114
    thumbnail_height: null
    thumbnail_small_width: 45
    thumbnail_small_height: null
    
  film:
    aws_s3_folder: 'films'
    maxfilesize: 5000000
    sourceimage_width: 480
    sourceimage_height: null
    thumbnail_width: 201
    thumbnail_height: null
    thumbnail_small_width: 73
    thumbnail_small_height: null
    background_path: %SF_WEB_DIR%/content/promovare/film_backgrounds
    background_path_for_web: /content/promovare/film_backgrounds

  homepage:
    aws_s3_folder: 'homepage_backgrounds'
    
  festival_edition:
    aws_s3_folder: 'festival_editions'
    maxfilesize: 5000000
    sourceimage_width: 678
    sourceimage_height: null
    thumbnail_width: 457
    thumbnail_height: null
    thumbnail_small_width: 45
    thumbnail_small_height: 45
    
  cinema:
    aws_s3_folder: 'cinemas'
    maxfilesize: 5000000
    sourceimage_width: 465
    sourceimage_height: null
    thumbnail_width: 126
    thumbnail_height: null
    thumbnail_small_width: 45
    thumbnail_small_height: null
    
  cinemapromotion:
    aws_s3_folder: 'cinemapromotions'
    maxfilesize: 5000000
    sourceimage_width: 465
    sourceimage_height: null
    thumbnail_width: 125
    thumbnail_height: null
    thumbnail_small_width: 45
    thumbnail_small_height: null
    
  article:
    aws_s3_folder: 'articles'
    maxfilesize: 5000000
    sourceimage_width: 210
    sourceimage_height: 210
    thumbnail_width: 210
    thumbnail_height: 210
    thumbnail_small_width: 210
    thumbnail_small_height: 210
    
  stire:
    aws_s3_folder: 'stires'
    maxfilesize: 5000000
    sourceimage_width: 300
    sourceimage_height: null
    thumbnail_width: 195
    thumbnail_height: null
    thumbnail_small_width: 195
    thumbnail_small_height: null
    
  shop:
    aws_s3_folder: 'shops'
    maxfilesize: 5000000
    sourceimage_width: 600
    sourceimage_height: 600
    thumbnail_width: 100
    thumbnail_height: 100
    thumbnail_small_width: 45
    thumbnail_small_height: 45
    
  rating: 
    types: ["AG - Audienta Generala", "N15", "IM 18", "AP12", "IM 18 XXX - Interzis minorilor si proiectiei cu public", "IC 14"]

  feedback:
    email: "feedback@filmsi.ro"

  contact:
    email: "contact@filmsi.ro"

  channel:
    aws_s3_folder: 'channels'
    maxfilesize: 5000000
    sourceimage_width: 465
    sourceimage_height: null
    thumbnail_width: 75
    thumbnail_height: null
    thumbnail_small_width: 75
    thumbnail_small_height: null

  content:
    name_1: 'Pagina "Contact"'
    name_2: 'Pagina "Termeni si conditii"'
    name_3: 'Pagina "Publicitate"'
    name_4: 'Celula sus din pagina "Publica stire"'
    name_5: 'Celula dreapta din pagina "Publica stire"'
    width_1: 660
    width_2: 660
    width_3: 660
    width_4: 450
    width_5: 200
    
  asset:
    aws_s3_folder: 'assets'
    
  aws:
    s3_path: "https://s3-eu-west-1.amazonaws.com/"
    key: "AKIAIATUBW7RP5FSHDHA"
    secret_key: "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"