<?php

/**
 * BoxofficeFilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoxofficeFilmTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoxofficeFilmTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BoxofficeFilm');
    }
}