<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
	public function getAllOrdered()
	{
		return Doctrine_Query::create()	
			->from('Category c')
			->orderBy('c.name ASC')
			->execute();
	}

	public function getForWidget()
	{
		$bruteCategorys = Doctrine_Query::create()
			->from('Category c')
			->orderBy('c.name ASC')
			->execute();
		
		$categorys = array('' => '');
		foreach ($bruteCategorys as $bruteCategory){
			$categorys[$bruteCategory->getName()] = $bruteCategory->getName();
		}
		
		return $categorys;
	}
}