<?php

/**
 * ChannelAlertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChannelAlertTable extends Doctrine_Table
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChannelAlert');
    }

	public function getByUser($userId)
	{
		return Doctrine_Query::create()
			->select('a.id, c.name channel_name, c.id channel_id')
			->from('ChannelAlert a')
			->innerJoin('a.Channel c')
			->where('a.user_id =?', $userId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
	}

	public function updateChannelsForUser($userId, $channelIds = array())
	{
		Doctrine_Query::create()
			->delete('ChannelAlert a')
			->where('a.user_id = ?', $userId)
			->execute();

		if (count($channelIds) > 0){
			foreach ($channelIds as $channelId){
				$channelAlert = new ChannelAlert();
				$channelAlert->setUserId($userId);
				$channelAlert->setChannelId($channelId);
				$channelAlert->save();
			}
		}
	}
    
}