<?php

/**
 * Channel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    channelsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Channel extends BaseChannel
{	
	public function preDelete($event)
	{
		// Delete the big file and the thumbnail
		unlink(sfConfig::get('app_channel_path') . '/' . $event->getInvoker()->getFilename());
		unlink(sfConfig::get('app_channel_path') . '/t-' . $event->getInvoker()->getFilename());
		unlink(sfConfig::get('app_channel_path') . '/ts-' . $event->getInvoker()->getFilename());

		return parent::preDelete($event);
	}
	
	public function createFile()
	{
		$sourceFile = sfConfig::get('app_channel_path') . '/' . $this->getFilename();
		
		if (!file_exists($sourceFile)){
			throw new sfException('Source file not available: ' . $sourceFile);
		}

		/* Create the big file */
		$photo = new sfThumbnail(sfConfig::get('app_channel_sourceimage_width'), sfConfig::get('app_channel_sourceimage_height'), true, false, 100);
		$photo->loadFile($sourceFile);
		$photo->save(sfConfig::get('app_channel_path') . '/' . $this->getFilename());

		/* Create the thumbnail */
		$thumb = new sfThumbnail(sfConfig::get('app_channel_thumbnail_width'), sfConfig::get('app_channel_thumbnail_height'), true, false, 100);
		$thumb->loadFile($sourceFile);
		$thumb->save(sfConfig::get('app_channel_path') . '/t-' . $this->getFilename());

		/* Create the small thumbnail */
		$thumb = new sfThumbnail(sfConfig::get('app_channel_thumbnail_small_width'), sfConfig::get('app_channel_thumbnail_small_height'), true, false, 100);
		$thumb->loadFile($sourceFile);
		$thumb->save(sfConfig::get('app_channel_path') . '/ts-' . $this->getFilename());
	}

	public function getFilmCount()
	{
		return ChannelScheduleTable::getInstance()->getFilmCountByChannel($this->getId());
	}
}