<?php

/**
 * CinemaServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaServiceTable extends Doctrine_Table
{
	public function deleteByServiceId($serviceId)
	{
		return Doctrine_Query::create()
			->delete('CinemaService cs')
			->where('cs.service_id = ?', $serviceId)
			->execute();
	}
}