<?php

/**
 * CinemaScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaScheduleTable extends Doctrine_Table
{
	public function getDetailedByCinema($cinemaId)
	{
		$scheduleBrutes = Doctrine_Query::create()
			->from('CinemaSchedule cs')
			->innerJoin('cs.Film f')
			->innerJoin('cs.Cinema c')
			->where('cs.cinema_id = ?', $cinemaId)
			->orderBy('cs.day ASC')
			->execute();
			
		$schedules = array();
		foreach ($scheduleBrutes as $scheduleBrute){
			$schedules[$scheduleBrute->getDay()][] = array(
				'id' => $scheduleBrute->getId(),
				'film' => $scheduleBrute->getFilm()->getName(),
				'schedule' => $scheduleBrute->getSchedule(),
				'format' => $scheduleBrute->getFormat()
			);
		}
		
		return $schedules;
	}
}