<?php

/**
 * CinemaArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaArticleTable extends Doctrine_Table
{
	public function updateObjects($articleId, $cinemas)
	{
		Doctrine_Query::create()
			->delete('CinemaArticle ca')
			->where('ca.article_id = ?', $articleId)
			->execute();
			
		foreach ($cinemas as $cinema){
			$cinemaArticle = new CinemaArticle();
			$cinemaArticle->setArticleId($articleId);
			$cinemaArticle->setCinemaId($cinema);
			$cinemaArticle->save();
		}
	}

	public function getRelatedArticles($articleId)
	{
		$cinemas = Doctrine_Query::create()
			->from('CinemaArticle fa')
			->where('fa.article_id = ?', $articleId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		$cinemaIds = array();
		foreach($cinemas as $cinema){
			$cinemaIds[] = $cinema['cinema_id'];
		}

		$articleIds = array();
                if (count($cinemaIds) > 0){
                    $articles = Doctrine_Query::create()
                            ->from('CinemaArticle ca')
                            ->whereIn('ca.cinema_id', $cinemaIds)
                            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
                    foreach($articles as $article){
                            $articleIds[] = $article['article_id'];
                    }
                }

		return $articleIds;
	}
}