<?php

/**
 * CinemaPromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaPromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CinemaPromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CinemaPromotion');
    }
}