<?php

/**
 * CinemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaTable extends Doctrine_Table
{
	public function allow($libraryId)
	{
		$album = Doctrine_Core::getTable('Cinema')->findOneByLibraryId($libraryId);
		
		/* Update album state*/
		$album->setState(Library::STATE_ACTIVE);
		$album->save();
	}

	public function cloneObject($libraryId)
	{
		$cinema = Doctrine_Core::getTable('Cinema')->findOneByLibraryId($libraryId);
		
		/* Cloning the object */
		$newCinema = new Cinema();
		$newCinema->setName($cinema->getName() . ' - clone');
		$newCinema->setLocationId($cinema->getLocationId());
		$newCinema->setAddress($cinema->getAddress());
		$newCinema->setPhone($cinema->getPhone());
		$newCinema->setWebsite($cinema->getWebsite());
		$newCinema->setLat($cinema->getLas());
		$newCinema->setLng($cinema->getLng());
		$newCinema->setSeats($cinema->getSeats());
		$newCinema->setSound($cinema->getSound());
		$newCinema->setTicketPrice($cinema->getTicketPrice());
		$newCinema->setIsTypeFilm($cinema->getIsTypeFilm());
		$newCinema->setIsTypeDigital($cinema->getIsTypeDigital());
		$newCinema->setIsType_3d($cinema->getIsType_3d());
		$newCinema->setDescriptionTeaser($cinema->getDescriptionTeaser());
		$newCinema->setDescriptionContent($cinema->getDescriptionContent());
		$newCinema->setMetaDescription($cinema->getMetaDescription());
		$newCinema->setMetaKeywords($cinema->getMetaKeywords());
		$newCinema->setPublishDate($cinema->getPublishDate());
		$newCinema->setState($cinema->getState());
		$newCinema->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
		$newCinema->setPhotoAlbumId($cinema->getPhotoAlbumId());
		$newCinema->setVideoAlbumId($cinema->getVideoAlbumId());
		
		
		$pieces = explode('.', $cinema->getFilename());
		$extension = $pieces[1];
		$newFilename = md5(time() . rand(0, 999999)) . '.' . $extension;
			
		/* Copying the photo files */
		copy(sfConfig::get('app_cinema_path') . '/' . $cinema->getFilename(), sfConfig::get('app_cinema_path') . '/' . $newFilename);
		copy(sfConfig::get('app_cinema_path') . '/t-' . $cinema->getFilename(), sfConfig::get('app_cinema_path') . '/t-' . $newFilename);
		copy(sfConfig::get('app_cinema_path') . '/ts-' . $cinema->getFilename(), sfConfig::get('app_cinema_path') . '/ts-' . $newFilename);
		
		$newCinema->setFilename($newFilename);
		$newCinema->save();
		
		/* Duplicating the relations to the services */
		$cinemaServices = Doctrine_Core::getTable('CinemaService')->findByCinemaId($cinema->getId());
		foreach ($cinemaServices as $cinemaService){
			$newCinemaService = new CinemaService();
			$newCinemaService->setCinemaId($newCinema->getId());
			$newCinemaService->setServiceId($cinemaService->getServiceId());
			$newCinemaService->save();
		}
	}

	public function getForApi($term)
	{
		$term = '(^| |-)' . $term ;
		
		$bruteCinemas = Doctrine_Query::create()
			->from('Cinema c')
			->andWhere('c.state = 1')
			->andWhere('c.name REGEXP ?', $term)
			->orderBy('c.name ASC')
			->limit(50)
			->execute();

    $cinemas = array();					              
		foreach ($bruteCinemas as $key => $bruteCinema){
			$cinemas[$key]['value'] = $bruteCinema->getId();
			$cinemas[$key]['label'] = $bruteCinema->getName();
		}
		
		return $cinemas;
	}
}