<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }

	public function getActiveByType($type, $ip)
	{	
		return Doctrine_Query::create()
			->from('Comment c')
			->where('c.type = ?', $type)
			->andWhere('c.state = 1 OR c.ip = ?', $ip)
			->execute();
	}

	public function getCountByEntity($type)
	{
		$q = Doctrine_Query::create()
			->from('Comment c')
			->select('COUNT(c.id) count')
			->where('c.type = ?', $type)
			->andWhere('c.state = 1')
			->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

		return $q['count'];
	}
}