<?php

/**
 * FestivalEditionVideoAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalEditionVideoAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FestivalEditionVideoAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FestivalEditionVideoAlbum');
    }
}