<?php

/**
 * FestivalEditionPhotoAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalEditionPhotoAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FestivalEditionPhotoAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FestivalEditionPhotoAlbum');
    }
}