<?php

/**
 * FestivalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalTable extends Doctrine_Table
{
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Festival');
	}

	public function getAllOrdered()
	{
		return Doctrine_Query::create()	
			->from('Festival f')
			->orderBy('f.name ASC')
			->execute();
	}
}