<?php

/**
 * FestivalEditionStireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalEditionStireTable extends Doctrine_Table
{
	public function updateObjects($stireId, $festivalEditions)
	{
		Doctrine_Query::create()
			->delete('FestivalEditionStire pa')
			->where('pa.stire_id = ?', $stireId)
			->execute();
			
		foreach ($festivalEditions as $festivalEdition){
			$festivalEditionStire = new FestivalEditionStire();
			$festivalEditionStire->setStireId($stireId);
			$festivalEditionStire->setFestivalEditionId($festivalEdition);
			$festivalEditionStire->save();
		}
	}

        public function getRelatedStires($stireId)
	{
		$festivalEditions = Doctrine_Query::create()
			->from('FestivalEditionStire fs')
			->where('fs.stire_id = ?', $stireId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		$festivalEditionIds = array();
		foreach($festivalEditions as $festivalEdition){
			$festivalEditionIds[] = $festivalEdition['festival_edition_id'];
		}

		$stireIds = array();
                if (count($festivalEditionIds) > 0){
                    $stires = Doctrine_Query::create()
                            ->from('FestivalEditionStire fs')
                            ->whereIn('fs.festival_edition_id', $festivalEditionIds)
                            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
                    foreach($stires as $stire){
                            $stireIds[] = $stire['stire_id'];
                    }
                }

		return $stireIds;
	}
}