<?php

/**
 * FestivalEditionStireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalEditionStireTable extends Doctrine_Table
{
	public function updateObjects($stireId, $festivalEditions)
	{
		Doctrine_Query::create()
			->delete('FestivalEditionStire pa')
			->where('pa.stire_id = ?', $stireId)
			->execute();
			
		foreach ($festivalEditions as $festivalEdition){
			$festivalEditionStire = new FestivalEditionStire();
			$festivalEditionStire->setStireId($stireId);
			$festivalEditionStire->setFestivalEditionId($festivalEdition);
			$festivalEditionStire->save();
		}
	}
}