<?php

/**
 * FestivalSectionParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FestivalSectionParticipantTable extends Doctrine_Table
{
	public function getBySectionAndFilmAndPerson($festivalSectionId, $filmImdb, $personImdb)
	{
		return Doctrine_Query::create()
			->from('FestivalSectionParticipant fsp')
			->where('fsp.festival_section_id = ? AND fsp.film_imdb = ? AND fsp.person_imdb = ?', array($festivalSectionId, $filmImdb, $personImdb))
			->fetchOne();
	}

	public function getBySectionAndFilmAndNullPerson($festivalSectionId, $filmImdb)
	{
		return Doctrine_Query::create()
			->from('FestivalSectionParticipant fsp')
			->where('fsp.festival_section_id = ? AND fsp.film_imdb = ? AND fsp.person_imdb IS NULL', array($festivalSectionId, $filmImdb))
			->fetchOne();
	}
}