<?php

/**
 * FilmEpisodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmEpisodeTable extends Doctrine_Table
{
    public function countByFilm($filmId)
	{
		$q = Doctrine_Query::create()
			->select('COUNT(DISTINCT fe.id) counter')
			->from('FilmEpisode fe')
			->where('fe.film_id = ?', $filmId)
			->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

		return $q['counter'];
	}

	public function getByFilm($filmId)
	{
		return Doctrine_Query::create()
			->from('FilmEpisode fe')
			->orderBy('fe.season, fe.number ASC')
			->where('fe.film_id = ?', $filmId)
			->execute();
	}
}