<?php

/**
 * FilmVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmVoteTable extends Doctrine_Table
{
        /**
         * Returns an instance of this class.
         *
         * @return object FilmVoteTable
         */
        public static function getInstance()
        {
            return Doctrine_Core::getTable('FilmVote');
        }

		public function deleteOlderThan($days)
        {
            Doctrine_Query::create()
                ->delete('FilmVote v')
                ->where('v.created_at < date_sub(NOW(), interval ? day)', $days)
                ->execute();
        }
        
}