<?php

/**
 * FilmStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FilmStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FilmStatus');
    }
}