<?php

/**
 * FilmStireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmStireTable extends Doctrine_Table
{
	public function updateObjects($stireId, $films)
	{
		Doctrine_Query::create()
			->delete('FilmStire fa')
			->where('fa.stire_id = ?', $stireId)
			->execute();
			
		foreach ($films as $film){
			$filmStire = new FilmStire();
			$filmStire->setStireId($stireId);
			$filmStire->setFilmId($film);
			$filmStire->save();
		}
	}
}