<?php

/**
 * FilmStireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmStireTable extends Doctrine_Table
{
	public function updateObjects($stireId, $films)
	{
		Doctrine_Query::create()
			->delete('FilmStire fa')
			->where('fa.stire_id = ?', $stireId)
			->execute();
			
		foreach ($films as $film){
			$filmStire = new FilmStire();
			$filmStire->setStireId($stireId);
			$filmStire->setFilmId($film);
			$filmStire->save();
		}
	}

        public function getRelatedStires($stireId)
	{
            $films = Doctrine_Query::create()
                    ->from('FilmStire fs')
                    ->where('fs.stire_id = ?', $stireId)
                    ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
            $filmIds = array();
            foreach($films as $film){
                    $filmIds[] = $film['film_id'];
            }

            $stireIds = array();
            if (count($filmIds) > 0){
                $stires = Doctrine_Query::create()
                        ->from('FilmStire fs')
                        ->whereIn('fs.film_id', $filmIds)
                        ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
                foreach($stires as $stire){
                        $stireIds[] = $stire['stire_id'];
                }
            }

            return $stireIds;
	}
}