<?php

/**
 * FilmGenreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FilmGenreTable extends Doctrine_Table
{
	public function deleteByGenreId($genreId)
	{
		return Doctrine_Query::create()
			->delete('FilmGenre fg')
			->where('fg.genre_id = ?', $genreId)
			->execute();
	}
}