<?php

/**
 * Homepage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Homepage extends BaseHomepage
{
	public function deleteBackground()
	{
		unlink(sfConfig::get('app_homepage_background_path') . '/' . $this->getBackgroundFilename());
		$this->setBackgroundFilename(NULL);
		$this->save();
	}

}