<?php

/**
 * HomepageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomepageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomepageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Homepage');
    }
}