<?php

/**
 * Library
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Library extends BaseLibrary
{
	const STATE_DRAFT = "-1";
	const STATE_PENDING = "0";
	const STATE_ACTIVE = "1";

	protected $types = array(
		'PhotoAlbum' => 'Album Foto',
		'VideoAlbum' => 'Album Video',
		'Person' => 'Persoana',
		'Film' => 'Film',
		'Cinema' => 'Cinematograf',
		'FestivalEdition' => 'Festival',
		'Stire' => 'Stire',
		'Article' => 'Articol'
	);

	public function getTypeName()
	{
		return $this->types[$this->getType()];
	}
}