<?php

/**
 * LocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationTable extends Doctrine_Table
{
	public function getForApi($term)
	{
		$term = '(^| |-)' . $term ;
		
		$bruteLocations = Doctrine_Query::create()
			->from('Location l')
			->andWhere('l.city REGEXP ?', $term)
			->orderBy('l.city ASC')
			->limit(50)
			->execute();

    $locations = array();					              
		foreach ($bruteLocations as $key => $bruteLocation){
			$locations[$key]['value'] = $bruteLocation->getId();
			$locations[$key]['label'] = $bruteLocation->getCity() . ', ' . $bruteLocation->getRegion();
		}
		
		return $locations;
	}
}