<?php

/**
 * NewsletterEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomepageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterEmail');
    }

	public function deleteByIds($ids)
	{
		return Doctrine_Query::create()
			->delete('NewsletterEmail e')
			->whereIn('e.id', $ids)
			->execute();
	}
}