<?php

/**
 * FilmGenreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageGadgetTable extends Doctrine_Table
{
	static public function getInstance()
	{
		return Doctrine_Core::getTable('PageGadget');
	}

	public function getPagesGroupedByGadget()
	{
		$pageGadgets = Doctrine_Query::create()
			->from('PageGadget g')
			->execute();

		$pagesByGadgets = array();
		foreach ($pageGadgets as $pageGadget){
			$pagesByGadgets[$pageGadget->getGadget()][] = $pageGadget->getPage();
		}

		return $pagesByGadgets;
	}

	public function getPagesByGadget($gadget)
	{
		$pageGadgets = Doctrine_Query::create()
			->from('PageGadget g')
			->where('g.gadget = ?', $gadget)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

		$pages = array();
		foreach($pageGadgets as $pageGadget){
			$pages[] = $pageGadget['page'];
		}

		return $pages;
	}

	public function updatePagesByGadget($gadget, $pages)
	{
		$q = Doctrine_Query::create()
			->delete('PageGadget g')
			->where('g.gadget = ?', $gadget)
			->execute();

		foreach ($pages as $page){
			$pageGadget = new PageGadget();
			$pageGadget->setPage($page);
			$pageGadget->setGadget($gadget);
			$pageGadget->save();
		}
	}
}