<?php

/**
 * PersonArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonArticleTable extends Doctrine_Table
{
	public function updateObjects($articleId, $persons)
	{
		Doctrine_Query::create()
			->delete('PersonArticle pa')
			->where('pa.article_id = ?', $articleId)
			->execute();
			
		foreach ($persons as $person){
			$personArticle = new PersonArticle();
			$personArticle->setArticleId($articleId);
			$personArticle->setPersonId($person);
			$personArticle->save();
		}
	}

	public function getRelatedArticles($articleId)
	{
		$persons = Doctrine_Query::create()
			->from('PersonArticle fa')
			->where('fa.article_id = ?', $articleId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		$personIds = array();
		foreach($persons as $person){
			$personIds[] = $person['person_id'];
		}
                
		$articleIds = array();
                if (count($personIds) > 0){
                    $articles = Doctrine_Query::create()
                            ->from('PersonArticle pa')
                            ->whereIn('pa.person_id', $personIds)
                            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
                    foreach($articles as $article){
                            $articleIds[] = $article['article_id'];
                    }
                }

		return $articleIds;
	}
}