<?php

/**
 * PersonStireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonStireTable extends Doctrine_Table
{
	public function updateObjects($stireId, $persons)
	{
		Doctrine_Query::create()
			->delete('PersonStire pa')
			->where('pa.stire_id = ?', $stireId)
			->execute();
			
		foreach ($persons as $person){
			$personStire = new PersonStire();
			$personStire->setStireId($stireId);
			$personStire->setPersonId($person);
			$personStire->save();
		}
	}

    public function getRelatedStires($stireId)
	{
		$persons = Doctrine_Query::create()
			->from('PersonStire fs')
			->where('fs.stire_id = ?', $stireId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		$personIds = array();
		foreach($persons as $person){
			$personIds[] = $person['person_id'];
		}

		$stireIds = array();
                if (count($personIds) > 0){
                    $stires = Doctrine_Query::create()
                            ->from('PersonStire fs')
                            ->whereIn('fs.person_id', $personIds)
                            ->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
                    foreach($stires as $stire){
                            $stireIds[] = $stire['stire_id'];
                    }
                }

		return $stireIds;
	}
}