<?php

/**
 * PersonVideoAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonVideoAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonVideoAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonVideoAlbum');
    }
}