<?php

/**
 * PersonAlertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonAlertTable extends Doctrine_Table
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonAlert');
    }

	public function deleteByUserAndPerson($userId, $personId)
	{
		return Doctrine_Query::create()
			->delete('PersonAlert fa')
			->where('fa.user_id = ? AND fa.person_id = ?', array($userId, $personId))
			->execute();
	}
}