<?php

/**
 * PersonPhotoAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonPhotoAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonPhotoAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonPhotoAlbum');
    }
}