<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
	public static function getInstance()
	{
		return Doctrine_Core::getTable('Photo');
	}

	public function getListForView($albumId)
	{
		return Doctrine_Query::create()
			->from('Photo p')
			->where('p.album_id = ?', $albumId)
			->orderBy('p.position ASC')
			->execute();
	}

	public function getFirst($albumId)
	{
		return Doctrine_Query::create()
			->from('Photo p')
			->where('p.album_id = ?', $albumId)
			->andWhere('p.position = 1')
			->fetchOne();
	}

	public function getNeighbours($albumId, $position)
	{
		$photos = Doctrine_Query::create()
			->from('Photo p')
			->select('p.id, p.position')
			->where('p.album_id = ?', $albumId)
			->whereIn('p.position', array($position - 1, $position + 1))
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
			
		$neighbours = array();
		 
		foreach($photos as $photo){
			if ($photo['position'] == $position - 1){
				$neighbours['previous'] = $photo;
			}

			if ($photo['position'] == $position + 1){
				$neighbours['next'] = $photo;
			}
		}
		 
		return $neighbours;
	}
	
	public function getCountByAlbum($albumId)
	{
		$q = Doctrine_Query::create()
			->select('COUNT(DISTINCT p.id) counter')
			->from('Photo p')		
			->where('p.album_id = ?', $albumId)
			->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
			
		return $q['counter'];
	}

	public function getLatestForFilms($limit = null)
	{
		$q = Doctrine_Query::create()
			->select('p.*, f.id, a.id, f.url_key, f.name_ro, f.name_en')
			->from('Photo p')
			->innerJoin('p.Album a')
			->innerJoin('a.Film f')
			->orderBy('p.updated_at DESC')
			->where('p.state = 1 AND a.publish_date IS NOT NULL AND a.publish_date <= NOW()');

		if (isset($limit)){
			$q = $q->limit($limit);
		}

		return $q->execute();

	}

	public function getLatestForFestivalEditions($limit = null)
	{
		$q = Doctrine_Query::create()
			->select('p.*, e.id, a.id, e.url_key, e.edition, f.name')
			->from('Photo p')
			->innerJoin('p.Album a')
			->innerJoin('a.FestivalEdition e')
			->innerJoin('e.Festival f')
			->orderBy('p.updated_at DESC')
			->where('p.state = 1 AND a.publish_date IS NOT NULL AND a.publish_date <= NOW()');

		if (isset($limit)){
			$q = $q->limit($limit);
		}

		return $q->execute();

	}
}