<?php

/**
 * ShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopTable extends Doctrine_Table
{
	public function getAllDetailed()
	{
		return Doctrine_Query::create()
			->select('s.*, COUNT(f.id) film_counter')
			->from('Shop s')
			->groupBy('s.id, f.id')
			->leftJoin('s.Films f')
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
	}
}