<?php

/**
 * ShopFilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopFilmTable extends Doctrine_Table
{
	static public function getInstance()
	{
		return Doctrine_Core::getTable('ShopFilm');
	}


	public function getDetailedByShop($shopId)
	{
		return Doctrine_Query::create()
			->from('ShopFilm fp')
			->innerJoin('fp.Film f')
			->where('fp.shop_id = ?', $shopId)
			->orderBy('f.name_ro')
			->execute();
	}

	public function getPagedByShop($shopId, $page, $limit)
	{
		return Doctrine_Query::create()
			->from('ShopFilm fp')
			->innerJoin('fp.Film f')
			->where('fp.shop_id = ?', $shopId)
			->orderBy('f.name_ro')
			->offset(($page - 1) * $limit)
			->limit($limit)
			->execute();
	}
	
	public function countByShop($shopId)
	{
		$q = Doctrine_Query::create()
			->select('COUNT(id) count')
			->from('ShopFilm f')
			->where('f.shop_id = ?', $shopId)
			->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
		
		return $q['count'];
	}


	public function update($filmDetails, $shopId)
	{
		Doctrine_Query::create()
			->delete('ShopFilm fp')
			->where('fp.shop_id = ?', $shopId)
			->execute();
			
		foreach ($filmDetails as $filmDetail){
			$shopFilm = new ShopFilm();
			$shopFilm->setFilmId($shopId);
			$shopFilm->setFilmId($filmDetail['id']);
			$shopFilm->setUrl($filmDetail['url']);
			$shopFilm->save();
		}
	}

	public function deleteByShopAndFilm($shopId, $filmId)
	{
		return Doctrine_Query::create()
			->delete('ShopFilm sf')
			->where('sf.shop_id = ? AND sf.film_id = ?', array($shopId, $filmId))
			->execute();
	}
	
	public function getByShopIdAndFilmId($shopId, $filmId)
	{
		return Doctrine_Query::create()
			->from('ShopFilm sf')
			->where('sf.shop_id = ? AND sf.film_id = ?', array($shopId, $filmId))
			->fetchOne();
	}

	public function deleteByShop($shopId)
	{
		return Doctrine_Query::create()
			->delete('ShopFilm sf')
			->where('sf.shop_id = ?', $shopId)
			->execute();
	}

}