<?php

/**
 * ShopFilmTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopFilmBufferTable extends Doctrine_Table
{
	static public function getInstance()
	{
		return Doctrine_Core::getTable('ShopFilmBuffer');
	}

	public function countByShop($shopId)
	{
		$q = Doctrine_Query::create()
			->select('COUNT(f.id) count')
			->from('ShopFilmBuffer f')
			->where('f.shop_id = ?', $shopId)
			->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
		
		return $q['count'];
	}

	public function deleteByShop($shopId)
	{
		return Doctrine_Query::create()
			->delete('ShopFilmBuffer sf')
			->where('sf.shop_id = ?', $shopId)
			->execute();
	}
	
	/* Gets and deletes a batch of films from the buffer */
	public function getBatch($shopId, $limit)
	{
		$bufferFilms = Doctrine_Query::create()
			->from('ShopFilmBuffer f')
			->limit($limit)
			->where('f.shop_id = ?', $shopId)
			->execute();
		
		Doctrine_Query::create()
			->delete('ShopFilmBuffer f')
			->limit($limit)
			->where('f.shop_id = ?', $shopId)
			->execute();
		
		return $bufferFilms;
	}
}