<?php

/**
 * StireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StireTable extends Doctrine_Table
{
	public function allow($libraryId)
	{
		$album = Doctrine_Core::getTable('Stire')->findOneByLibraryId($libraryId);
		
		/* Update album state*/
		$album->setState(Library::STATE_ACTIVE);
		$album->save();
	}

	public function cloneObject($libraryId)
	{
		return;
	}
}