<?php

/**
 * VideoAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VideoAlbum extends BaseVideoAlbum
{
	public function preDelete($event)
	{
		$videos = Doctrine_Core::getTable('Video')->findByAlbumId($event->getInvoker()->getId());
		
		if ($videos->count() > 0) {
			$videos->delete();	
		}

		/* Delete from all the elemets that are tied to this album */
		ArticleTable::getInstance()->cleanVideoAlbums($event->getInvoker()->getId());
		FilmTable::getInstance()->cleanVideoAlbums($event->getInvoker()->getId());
		FestivalEditionTable::getInstance()->cleanVideoAlbums($event->getInvoker()->getId());
		PersonTable::getInstance()->cleanVideoAlbums($event->getInvoker()->getId());
		StireTable::getInstance()->cleanVideoAlbums($event->getInvoker()->getId());
	}

	public function getCover()
	{
	}

	/**
	 * Returns the number of videos in this album
	 */
	public function getVideoCount()
	{
		return Doctrine_Core::getTable('Video')->getCountByAlbum($this->getId());
	}
}