<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
	public function preInsert($event)
	{
		if (sfContext::getInstance()->getUser()->hasCredential(array('Fara_moderare', 'Moderator'), false)){
			$event->getInvoker()->setState(Library::STATE_ACTIVE);	
		} else {
			$event->getInvoker()->setState(Library::STATE_PENDING);
		}
	}
	
	public function getUrlInParentGallery()
	{
		/* Check if the parent album belongs to any film */
		if ( false !== $film = FilmTable::getInstance()->findOneByVideoAlbumId($this->getAlbumId())) {
			return sfContext::getInstance()->getRouting()->generate('film_videos', array('id' => $film->getId(), 'key' => $film->getUrlKey())) . '?vid=' . $this->getPosition() . '#scrolled';
		}
		
		/* Check if the parent album belongs to any film */
		if ( false !== $cinema = CinemaTable::getInstance()->findOneByVideoAlbumId($this->getAlbumId())) {
			return sfContext::getInstance()->getRouting()->generate('cinema_videos', array('id' => $cinema->getId(), 'key' => $cinema->getUrlKey())) . '?vid=' . $this->getPosition() . '#scrolled';
		}
		
		/* Check if the parent album belongs to any film */
		if ( false !== $person = PersonTable::getInstance()->findOneByVideoAlbumId($this->getAlbumId())) {
			return sfContext::getInstance()->getRouting()->generate('person_videos', array('id' => $person->getId(), 'key' => $person->getUrlKey())) . '?vid=' . $this->getPosition() . '#scrolled';
		}
		
		return false;
	}

}