<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    filmsi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
	public function preInsert($event)
	{
		if (sfContext::getInstance()->getUser()->hasCredential(array('Fara_moderare', 'Moderator'), false)){
  		$event->getInvoker()->setState(Library::STATE_ACTIVE);	
  	} else {
  		$event->getInvoker()->setState(Library::STATE_PENDING);
  	}
	}

}