# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  article:
    page_limit: 10
  stire:
    page_limit: 20
  persons:
    page_limit: 20
  trailer:
    page_limit: 20
  festival:
    page_limit: 20
  film_in_cinema:
    page_limit: 20
