# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }

forgot_password:
  url:   /request_password
  param: { module: user, action: password }

articles:
  url: /articole
  param: { module: articles, action: index }

article:
  url: /articol/:id/:key
  param: { module: articles, action: view }

article_no_key:
  url: /articol/:id/
  param: { module: articles, action: view }

stires:
  url: /stiri
  param: { module: stires, action: index }

stire:
  url: /stire/:id/:key
  param: { module: stires, action: view }

stire_no_key:
  url: /stire/:id/
  param: { module: stires, action: view }

stire_publish:
  url: /publica-stire
  param: { module: stires, action: publish }

directors:
  url: /regizori
  param: { module: persons, action: directors }

directors_by_letter:
  url: /regizori/:letter
  param: { module: persons, action: directorsByLetter }

actors:
  url: /actori
  param: { module: persons, action: actors }

actors_by_letter:
  url: /actori/:letter
  param: { module: persons, action: actorsByLetter }

persons:
  url: /actori-si-regizori
  param: { module: persons, action: index }

persons_by_letter:
  url: /actori-si-regizori/:letter
  param: { module: persons, action: indexByLetter }

person_biography:
  url: /biografie/:id/:key
  param: { module: persons, action: biography }

person_biography_no_key:
  url: /biografie/:id/
  param: { module: persons, action: biography }

person_films:
  url: /filmografie/:id/:key
  param: { module: persons, action: films }

person_films_no_key:
  url: /filmografie/:id/
  param: { module: persons, action: films }

person_awards:
  url: /premii-castigate-de/:id/:key
  param: { module: persons, action: awards }

person_awards_no_key:
  url: /premii-castigate-de/:id/
  param: { module: persons, action: awards }

person_stiri:
  url: /stiri-despre/:id/:key
  param: { module: persons, action: stiri }

person_stiri_no_key:
  url: /stiri-despre/:id/
  param: { module: persons, action: stiri }

person_photos:
  url: /fotografii-persoana/:id/:key
  param: { module: persons, action: photos }

person_photos_no_key:
  url: /fotografii-persoana/:id/
  param: { module: persons, action: photos }

person:
  url: /persoana/:id/:key
  param: { module: persons, action: view, person_role: 'actor' }

person_no_key:
  url: /persoana/:id/
  param: { module: persons, action: view, person_role: 'actor' }

actor:
  url: /actor/:id/:key
  param: { module: persons, action: view, person_role: 'actor' }

actor_no_key:
  url: /actor/:id/
  param: { module: persons, action: view, person_role: 'actor' }

director:
  url: /regizor/:id/:key
  param: { module: persons, action: view, person_role: 'director' }

director_no_key:
  url: /regizor/:id/
  param: { module: persons, action: view, person_role: 'director' }

scriptwriter:
  url: /scenarist/:id/:key
  param: { module: persons, action: view, person_role: 'scriptwriter' }

scriptwriter_no_key:
  url: /scenarist/:id/
  param: { module: persons, action: view, person_role: 'scriptwriter' }

producer:
  url: /producator/:id/:key
  param: { module: persons, action: view, person_role: 'producer' }

producer_no_key:
  url: /producator/:id/
  param: { module: persons, action: view, person_role: 'producer' }












films:
  url: /films
  param: { module: films, action: index }

film:
  url: /film/:id/:key
  param: { module: films, action: view }

film_no_key:
  url: /film/:id/
  param: { module: films, action: view }

film_buy:
  url: /cumpara-film/:id/:key
  param: { module: films, action: buy }

film_buy_no_key:
  url: /cumpara-film/:id/
  param: { module: films, action: buy }

film_tickets:
  url: /rezerva-bilete-film/:id/:key
  param: { module: films, action: tickets }

film_tickets_no_key:
  url: /rezerva-bilete-film/:id/
  param: { module: films, action: tickets }

film_cast:
  url: /echipa-film/:id/:key
  param: { module: films, action: cast }

film_cast_no_key:
  url: /echipa-film/:id/
  param: { module: films, action: cast }

film_sinopsis:
  url: /sinopsis-film/:id/:key
  param: { module: films, action: sinopsis }

film_sinopsis_no_key:
  url: /sinopsis-film/:id/
  param: { module: films, action: sinopsis }

film_awards:
  url: /premii-film/:id/:key
  param: { module: films, action: awards }

film_awards_no_key:
  url: /premii-film/:id/
  param: { module: films, action: awards }

film_articles:
  url: /articole-film/:id/:key
  param: { module: films, action: articles }

film_articles_no_key:
  url: /articole-film/:id/
  param: { module: films, action: articles }

film_comments:
  url: /comentarii-film/:id/:key
  param: { module: films, action: comments }

film_comments_no_key:
  url: /comentarii-film/:id/
  param: { module: films, action: comments }

film_photos:
  url: /fotografii-film/:id/:key
  param: { module: films, action: photos }

film_photos_no_key:
  url: /fotografii-film/:id/
  param: { module: films, action: photos }

film_redcarpet:
  url: /fotografii-de-la-premiera-film/:id/:key
  param: { module: films, action: redcarpet }

film_redcarpet_no_key:
  url: /fotografii-de-la-premiera-film/:id/
  param: { module: films, action: redcarpet }

film_videos:
  url: /video-film/:id/:key
  param: { module: films, action: videos }

film_videos_no_key:
  url: /video-film/:id/
  param: { module: films, action: videos }

film_stiri:
  url: /stiri-film/:id/:key
  param: { module: films, action: stiri }

film_stiri_no_key:
  url: /stiri-film/:id/
  param: { module: films, action: stiri }

film_vote:
  url: /film-vote/
  param: { module: films, action: vote }

film_now_in_cinema:
  url: /filme-acum-in-cinema
  param: { module: films, action: nowInCinema }

film_soon_in_cinema:
  url: /filme-in-curand-in-cinema
  param: { module: films, action: soonInCinema }

film_day_in_cinema:
  url: /filme-in-cinema-in-data-de/:day
  param: { module: films, action: dayInCinema }

film_now_on_dvd:
  url: /filme-acum-pe-dvd-si-bluray
  param: { module: films, action: nowOnDvd }

film_soon_on_dvd:
  url: /filme-in-curand-pe-dvd-si-bluray
  param: { module: films, action: soonOnDvd }

film_on_tv:
  url: /filme-la-tv
  param: { module: films, action: onTv }




trailers:
  url: /trailere
  param: { module: trailers, action: index }

trailer:
  url: /trailere/:id
  param: { module: trailers, action: index }






festivals:
  url: /festivaluri
  param: { module: awards, action: index }

festival:
  url: /festivaluri/:id
  param: { module: awards, action: index }
  
festival_edition:
  url: /festival/:id/:key
  param: { module: awards, action: view }

festival_edition_no_key:
  url: /festival/:id/
  param: { module: awards, action: view }

festival_edition_judges:
  url: /juriu-festival/:id/:key
  param: { module: awards, action: judges }

festival_edition_judges_no_key:
  url: /juriu-festival/:id/
  param: { module: awards, action: judges }

festival_edition_articles:
  url: /articole-festival/:id/:key
  param: { module: awards, action: articles }

festival_edition_articles_no_key:
  url: /articole-festival/:id/
  param: { module: awards, action: articles }

festival_edition_winners:
  url: /castigatori-si-nominalizati-festival/:id/:key
  param: { module: awards, action: winners }

festival_edition_winners_no_key:
  url: /castigatori-si-nominalizati-festival/:id/
  param: { module: awards, action: winners }

festival_edition_photos:
  url: /fotografii-festival/:id/:key
  param: { module: awards, action: photos }

festival_edition_photos_no_key:
  url: /fotografii-festival/:id/
  param: { module: awards, action: photos }

festival_edition_videos:
  url: /video-festival/:id/:key
  param: { module: awards, action: videos }

festival_edition_videos_no_key:
  url: /video-festival/:id/
  param: { module: awards, action: videos }

festival_edition_stiri:
  url: /stiri-festival/:id/:key
  param: { module: awards, action: stiri }

festival_edition_stiri_no_key:
  url: /stiri-festival/:id/
  param: { module: awards, action: stiri }















cinemas:
  url: /cinematografe
  param: { module: cinemas, action: index }

cinemas_by_region:
  url: /cinematografe/:region
  param: { module: cinemas, action: index }

cinema:
  url: /cinematograf/:id/:key
  param: { module: cinemas, action: view }

cinema_no_key:
  url: /cinematograf/:id/
  param: { module: cinemas, action: view }

cinema_schedule:
  url: /program-cinema/:id/:key
  param: { module: cinemas, action: schedule }

cinema_schedule_no_key:
  url: /program-cinema/:id/
  param: { module: cinemas, action: schedule }

cinema_description:
  url: /prezentare-cinema/:id/:key
  param: { module: cinemas, action: description }

cinema_description_no_key:
  url: /prezentare-cinema/:id/
  param: { module: cinemas, action: description }

cinema_tickets:
  url: /pret-bilete-cinema/:id/:key
  param: { module: cinemas, action: tickets }

cinema_tickets_no_key:
  url: /pret-bilete-cinema/:id/
  param: { module: cinemas, action: tickets }

cinema_promotions:
  url: /promotii-cinema/:id/:key
  param: { module: cinemas, action: promotions }

cinema_promotions_no_key:
  url: /promotii-cinema/:id/
  param: { module: cinemas, action: promotions }

cinema_promotion_edit:
  url: /editeaza-promotie/:id
  param: { module: cinemas, action: promotionEdit }

cinema_comments:
  url: /comentarii-cinema/:id/:key
  param: { module: cinemas, action: comments }

cinema_comments_no_key:
  url: /comentarii-cinema/:id/
  param: { module: cinemas, action: comments }

cinema_photos:
  url: /fotografii-cinema/:id/:key
  param: { module: cinemas, action: photos }

cinema_photos_no_key:
  url: /fotografii-cinema/:id/
  param: { module: cinemas, action: photos }

cinema_stiri:
  url: /stiri-cinema/:id/:key
  param: { module: cinemas, action: stiri }

cinema_stiri_no_key:
  url: /stiri-cinema/:id/
  param: { module: cinemas, action: stiri }

cinema_vote:
  url: /cinema-vote/
  param: { module: cinemas, action: vote }

cinema_search:
  url: /program-cinema
  param: { module: cinemas, action: search }











festivaleditions:
  url: /festivaluri
  param: { module: festivaleditions, action: index }

festivaledition:
  url: /festival/:id/:key
  param: { module: festivaleditions, action: view }
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
