# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }

forgot_password:
  url:   /request_password
  param: { module: user, action: password }

articles:
  url: /articole
  param: { module: articles, action: index }

article:
  url: /articol/:id/:key
  param: { module: articles, action: view }

article_no_key:
  url: /articol/:id/
  param: { module: articles, action: view }

stires:
  url: /stiri
  param: { module: stires, action: index }

stire:
  url: /stire/:id/:key
  param: { module: stires, action: view }

stire_no_key:
  url: /stire/:id/
  param: { module: stires, action: view }

stire_publish:
  url: /publica-stire
  param: { module: stires, action: publish }

directors:
  url: /regizori
  param: { module: persons, action: directors }

directors_by_letter:
  url: /regizori/:letter
  param: { module: persons, action: directorsByLetter }

actors:
  url: /actori
  param: { module: persons, action: actors }

actors_by_letter:
  url: /actori/:letter
  param: { module: persons, action: actorsByLetter }

persons:
  url: /actori-si-regizori
  param: { module: persons, action: index }

persons_by_letter:
  url: /actori-si-regizori/:letter
  param: { module: persons, action: indexByLetter }

person_biography:
  url: /biografie/:id/:key
  param: { module: persons, action: biography }

person_biography_no_key:
  url: /biografie/:id/
  param: { module: persons, action: biography }

person_films:
  url: /filmografie/:id/:key
  param: { module: persons, action: films }

person_films_no_key:
  url: /filmografie/:id/
  param: { module: persons, action: films }

person_awards:
  url: /premii-castigate-de/:id/:key
  param: { module: persons, action: awards }

person_awards_no_key:
  url: /premii-castigate-de/:id/
  param: { module: persons, action: awards }

person_stiri:
  url: /stiri-despre/:id/:key
  param: { module: persons, action: stiri }

person_stiri_no_key:
  url: /stiri-despre/:id/
  param: { module: persons, action: stiri }

person_photos:
  url: /fotografii-persoana/:id/:key
  param: { module: persons, action: photos }

person_photos_no_key:
  url: /fotografii-persoana/:id/
  param: { module: persons, action: photos }

person:
  url: /persoana/:id/:key
  param: { module: persons, action: view, person_role: 'actor' }

person_no_key:
  url: /persoana/:id/
  param: { module: persons, action: view, person_role: 'actor' }

actor:
  url: /actor/:id/:key
  param: { module: persons, action: view, person_role: 'actor' }

actor_no_key:
  url: /actor/:id/
  param: { module: persons, action: view, person_role: 'actor' }

director:
  url: /regizor/:id/:key
  param: { module: persons, action: view, person_role: 'director' }

director_no_key:
  url: /regizor/:id/
  param: { module: persons, action: view, person_role: 'director' }

scriptwriter:
  url: /scenarist/:id/:key
  param: { module: persons, action: view, person_role: 'scriptwriter' }

scriptwriter_no_key:
  url: /scenarist/:id/
  param: { module: persons, action: view, person_role: 'scriptwriter' }

producer:
  url: /producator/:id/:key
  param: { module: persons, action: view, person_role: 'producer' }

producer_no_key:
  url: /producator/:id/
  param: { module: persons, action: view, person_role: 'producer' }












films:
  url: /films
  param: { module: films, action: index }

film:
  url: /film/:id/:key
  param: { module: films, action: view }

film_buy:
  url: /cumpara-film/:id/:key
  param: { module: films, action: buy }

film_buy_no_key:
  url: /cumpara-film/:id/
  param: { module: films, action: buy }





















cinemas:
  url: /cinematografe
  param: { module: cinemas, action: index }

cinema:
  url: /cinematograf/:id/:key
  param: { module: cinemas, action: view }

festivaleditions:
  url: /festivaluri
  param: { module: festivaleditions, action: index }

festivaledition:
  url: /festival/:id/:key
  param: { module: festivaleditions, action: view }
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
